{% set version = "0.3.6.0" %}

{% set crossref_ver = "0.3.5.0b" %}
{% set pandoc_unix_ver = "2_8_1" %}
{% set pandoc_win_ver = "2.8.1" %}

package:
  name: pandoc-crossref
  version: {{ version }}

source:
  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ crossref_ver }}/linux-pandoc_{{ pandoc_unix_ver }}.tar.gz  # [linux64]
  sha256: 238baa837b4ffa194d3a24e89580050c1746ea875f1a1dc67b2c983d283d233a  # [linux64]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ crossref_ver }}/macos-pandoc_{{ pandoc_unix_ver }}.tar.gz  # [osx]
  sha256: 4cfa327aea7a967ed1e64630b5d06c1935fa6ae274b1423e9f2aafb98bd39e62  # [osx]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ crossref_ver }}/windows-x86_64-pandoc_{{ pandoc_win_ver }}.zip  # [win]
  sha256: f8f13929d1ecfc7e6bf4f3a7b4c06c5deaa5e6c4b8a57b89b550a38ca30feec5  # [win]

build:
   number: 0

requirements:
  run:
    - pandoc >=2.8.1,<2.9

test:
  commands:
    - pandoc-crossref --help
    - pandoc-crossref --version

about:
  home: https://github.com/lierdakil/pandoc-crossref
  license: GPL-2.0
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Pandoc filter for cross-references'
  doc_url: https://lierdakil.github.io/pandoc-crossref/
  dev_url: https://github.com/lierdakil/pandoc-crossref

extra:
  recipe-maintainers:
    - kiwi0fruit
