{% set version = "0.3.8.2" %}
{% set postf1 = "" %}
{% set postf2 = "" %}
{% set pandoc = "2.11" %}
{% set pandoc1 = "2.12" %}

package:
  name: pandoc-crossref
  version: {{ version }}{{ postf1 }}

source:
  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}{{ postf2 }}/pandoc-crossref-Linux.tar.xz  # [linux64]
  sha256: b3ccaf4d0d9f1982079f1d4097364e12ddf69a9457fae75cd8c741056502ba5b  # [linux64]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}{{ postf2 }}/pandoc-crossref-macOS.tar.xz  # [osx]
  sha256: d40cf2e583f5b786335248e06d3dfc6bd690b979ca9ed64e83d07e0ac8f73345  # [osx]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}{{ postf2 }}/pandoc-crossref-Windows.7z  # [win]
  sha256: 6c0492b90f6d3419ff754a1c45558ea317630e0795c534341db788c3c41f86ea  # [win]

build:
   number: 0

requirements:
  run:
    - pandoc >={{ pandoc }},<{{ pandoc1 }}

test:
  commands:
    - pandoc-crossref --help
    - pandoc-crossref --version

about:
  home: https://github.com/lierdakil/pandoc-crossref
  license: GPL-2.0
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Pandoc filter for cross-references'
  doc_url: https://lierdakil.github.io/pandoc-crossref/
  dev_url: https://github.com/lierdakil/pandoc-crossref

extra:
  recipe-maintainers:
    - kiwi0fruit
